services:
  - type: web
    name: name-analysis-api
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: SUPABASE_URL
        value: "your-supabase-url"
      - key: SUPABASE_KEY
        value: "your-supabase-key"
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=${PORT}"
